"""add_broadcast_notifications

Revision ID: 0a37040b3fd1
Revises: 96b2a4267795
Create Date: 2026-06-17 14:08:42.125186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a37040b3fd1'
down_revision: Union[str, Sequence[str], None] = '96b2a4267795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_reads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'notification_id')
    )
    op.create_index(op.f('ix_user_notification_reads_notification_id'), 'user_notification_reads', ['notification_id'], unique=False)
    op.create_index(op.f('ix_user_notification_reads_user_id'), 'user_notification_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_reads_user_id'), table_name='user_notification_reads')
    op.drop_index(op.f('ix_user_notification_reads_notification_id'), table_name='user_notification_reads')
    op.drop_table('user_notification_reads')
    op.drop_table('notifications')
    # ### end Alembic commands ###
