"""add_updated_at_to_user_workout_stats

Revision ID: 2bd80291c06b
Revises: d8a93a8442f4
Create Date: 2026-06-17 11:08:14.161322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd80291c06b'
down_revision: Union[str, Sequence[str], None] = 'd8a93a8442f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workout_stats', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_workout_stats', 'updated_at')
    # ### end Alembic commands ###
