"""add icon_public_id to muscle_group

Revision ID: 611684825312
Revises: d3c06cd3134f
Create Date: 2026-06-16 14:36:46.168549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611684825312'
down_revision: Union[str, Sequence[str], None] = 'd3c06cd3134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muscle_groups', sa.Column('icon_public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muscle_groups', 'icon_public_id')
    # ### end Alembic commands ###
