"""add_blog_categories

Revision ID: 96b2a4267795
Revises: 2bd80291c06b
Create Date: 2026-06-17 12:50:00.100749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b2a4267795'
down_revision: Union[str, Sequence[str], None] = '2bd80291c06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('blogs', sa.Column('category_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'blogs', 'blog_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###

    # Seed categories
    blog_categories_table = sa.table(
        'blog_categories',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('slug', sa.String)
    )

    import uuid
    categories = [
        {"id": str(uuid.uuid4()), "name": "Workout", "slug": "workout"},
        {"id": str(uuid.uuid4()), "name": "Nutrition", "slug": "nutrition"},
        {"id": str(uuid.uuid4()), "name": "Weight Loss", "slug": "weight-loss"},
        {"id": str(uuid.uuid4()), "name": "Muscle Gain", "slug": "muscle-gain"},
        {"id": str(uuid.uuid4()), "name": "Recovery", "slug": "recovery"},
        {"id": str(uuid.uuid4()), "name": "Supplements", "slug": "supplements"},
        {"id": str(uuid.uuid4()), "name": "Lifestyle", "slug": "lifestyle"},
    ]
    op.bulk_insert(blog_categories_table, categories)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'category_id')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
