"""add media blog and nutrition chart tables

Revision ID: d3c06cd3134f
Revises: e05f2e981945
Create Date: 2026-06-12 18:01:23.272913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3c06cd3134f'
down_revision: Union[str, Sequence[str], None] = 'e05f2e981945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop old table and index first
    op.drop_index(op.f('ix_exercise_media_exercise_id'), table_name='exercise_media')
    op.drop_table('exercise_media')
    
    # 2. Drop the old enum types so they can be recreated
    op.execute("DROP TYPE IF EXISTS storage_provider_enum")
    op.execute("DROP TYPE IF EXISTS media_type_enum")
    
    # 3. Create the new tables and types
    op.create_table('media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('exercise', 'blog', 'diet_chart', 'workout_plan', 'user_profile', name='entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='media_type_enum'), nullable=False),
    sa.Column('provider', sa.Enum('cloudinary', 'azure', 'aws', name='storage_provider_enum'), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('cdn_url', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('public_id', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_entity_id'), 'media', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_entity_type'), 'media', ['entity_type'], unique=False)
    op.create_table('blogs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_created_by'), 'blogs', ['created_by'], unique=False)
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    op.create_table('nutrition_charts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('diet_plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition_charts')
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_created_by'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_media_entity_type'), table_name='media')
    op.drop_index(op.f('ix_media_entity_id'), table_name='media')
    op.drop_table('media')
    
    # Drop the new/recreated enum types
    op.execute("DROP TYPE IF EXISTS entity_type_enum")
    op.execute("DROP TYPE IF EXISTS storage_provider_enum")
    op.execute("DROP TYPE IF EXISTS media_type_enum")
    
    # Recreate the old table and index
    op.create_table('exercise_media',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('media_type', postgresql.ENUM('image', 'video', name='media_type_enum'), autoincrement=False, nullable=False),
    sa.Column('provider', postgresql.ENUM('azure', 'aws', name='storage_provider_enum'), autoincrement=False, nullable=False),
    sa.Column('storage_key', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('cdn_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('file_size_kb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('exercise_media_exercise_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('exercise_media_pkey'))
    )
    op.create_index(op.f('ix_exercise_media_exercise_id'), 'exercise_media', ['exercise_id'], unique=False)
    # ### end Alembic commands ###
