"""add_workout_date_to_user_workout_stats

Revision ID: d8a93a8442f4
Revises: ffc14af50bff
Create Date: 2026-06-17 10:42:18.891904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a93a8442f4'
down_revision: Union[str, Sequence[str], None] = 'ffc14af50bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable first
    op.add_column('user_workout_stats', sa.Column('workout_date', sa.Date(), nullable=True))
    
    # 2. Populate existing rows using the date from created_at
    op.execute("UPDATE user_workout_stats SET workout_date = CAST(created_at AS DATE)")
    
    # 3. Set nullable to False
    op.alter_column('user_workout_stats', 'workout_date', nullable=False)
    
    # 4. Create index
    op.create_index(op.f('ix_user_workout_stats_workout_date'), 'user_workout_stats', ['workout_date'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_workout_stats_workout_date'), table_name='user_workout_stats')
    op.drop_column('user_workout_stats', 'workout_date')
    # ### end Alembic commands ###
