"""add_indexes_and_refactor_exercises

Revision ID: f16ce4041cd4
Revises: f02edd1d5753
Create Date: 2026-06-10 17:33:12.192975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16ce4041cd4'
down_revision: Union[str, Sequence[str], None] = 'f02edd1d5753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_exercise_media_exercise_id'), 'exercise_media', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercises_created_by'), 'exercises', ['created_by'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_group_id'), 'exercises', ['muscle_group_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_workout_day_exercises_day_id'), 'workout_day_exercises', ['day_id'], unique=False)
    op.create_index(op.f('ix_workout_day_exercises_exercise_id'), 'workout_day_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_days_plan_id'), 'workout_days', ['plan_id'], unique=False)
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_days_plan_id'), table_name='workout_days')
    op.drop_index(op.f('ix_workout_day_exercises_exercise_id'), table_name='workout_day_exercises')
    op.drop_index(op.f('ix_workout_day_exercises_day_id'), table_name='workout_day_exercises')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_exercises_muscle_group_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_by'), table_name='exercises')
    op.drop_index(op.f('ix_exercise_media_exercise_id'), table_name='exercise_media')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    # ### end Alembic commands ###
