"""create user workout stats table

Revision ID: ffc14af50bff
Revises: 1fcfdb092684
Create Date: 2026-06-16 19:06:36.556014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc14af50bff'
down_revision: Union[str, Sequence[str], None] = '1fcfdb092684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_workout_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workout_plan_id', sa.String(length=36), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_label', sa.String(length=100), nullable=True),
    sa.Column('exercises_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_workout_stats_user_id'), 'user_workout_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_workout_stats_workout_plan_id'), 'user_workout_stats', ['workout_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_workout_stats_workout_plan_id'), table_name='user_workout_stats')
    op.drop_index(op.f('ix_user_workout_stats_user_id'), table_name='user_workout_stats')
    op.drop_table('user_workout_stats')
    # ### end Alembic commands ###
